### ISSUE TITLE
Deserializing into slice returns a pointer to stack-allocated array

### ISSUE THREAD

**Issue by sharpobject** [Luukdegram/mzg_pack#1]
Hello, I think when deserializing into a slice we need to allocate an array to back the slice in the buffer.

https://github.com/Luukdegram/mzg_pack/blob/f7107956530255e1af3a2558cadfd022873b55dd/src/main.zig#L238

**Comment by Luukdegram** [comment]
In stage1 this is legal, due to arrays having a static lifetime. However, we'll definitely have to allocate this or use the buffer that was provided by the user, as it's currently hardcoded to a max of 1024 elements. Which obviously may be too small for certain messages.

**Comment by sharpobject** [comment]
I don't think that's correct. For example, this program does not print "Hello, World!" twice in a debug build built with zig 0.8.0:

```
const std = @import("std");

pub fn blorp() []u8 {
    var xd: [13]u8 = "Hello, World!";
    std.log.info("msg: {s}", .{xd[0..13]});
    return xd[0..13];
}

pub fn printpls(msg: []u8) void {
    var xd: [1000]u8 = undefined;
    std.log.info("msg: {s}", .{msg});
}

pub fn main() anyerror!void {
    const hello = blorp();
    printpls(hello);
}
```

**Comment by Luukdegram** [comment]
A more representable example would be https://godbolt.org/z/8P4Tr7nYf as it's the user's responsibility to ensure the lifetime of the return value. Either way, you are definitely right that this should be handled differently, such as the solution I pointed out earlier.
